name: cape

channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11.11
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.8.0
  - torchvision=0.17.0
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - xgboost=2.1.1
  - joblib=1.4.2
  - tqdm=4.66.6
  - catboost=1.2
  - seaborn=0.13.2
  - timm=1.0.15
